apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  realm-export.json: |
    {
      "realm": "degree-flowchart",
      "enabled": true,
      "users": [
        {
          "username": "student1",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "student123"
            }
          ],
          "realmRoles": [
            "student"
          ],
          "clientRoles": {
            "degree-edge-service": [
              "user"
            ]
          }
        }
      ],
      "clients": [
        {
          "clientId": "degree-edge-service",
          "enabled": true,
          "publicClient": false,
          "secret": "client-secret",
          "redirectUris": [
            "http://localhost:9000/login/oauth2/code/keycloak",
            "http://localhost:4200/*"
          ],
          "webOrigins": [
            "*"
          ],
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": true
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "student",
            "description": "Student Role"
          }
        ]
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0.0
        args: ["start-dev", "--import-realm"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_HOSTNAME
          value: localhost
        - name: KC_HOSTNAME_PORT
          value: "8080"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
        volumeMounts:
        - name: realm-config
          mountPath: /opt/keycloak/data/import/realm-export.json
          subPath: realm-export.json
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: realm-config
        configMap:
          name: keycloak-realm-config
